var group__io__interfaces =
[
    [ "ADC driver APIs", "group__adc__interface.html", "group__adc__interface" ],
    [ "CAN Interface", "group__can__interface.html", "group__can__interface" ],
    [ "Clock Control Interface", "group__clock__control__interface.html", "group__clock__control__interface" ],
    [ "Counter Interface", "group__counter__interface.html", "group__counter__interface" ],
    [ "DAC driver APIs", "group__dac__interface.html", "group__dac__interface" ],
    [ "DMA Interface", "group__dma__interface.html", "group__dma__interface" ],
    [ "EC Host Command Interface", "group__ec__host__cmd__periph__interface.html", "group__ec__host__cmd__periph__interface" ],
    [ "EDAC API", "group__edac.html", "group__edac" ],
    [ "EEPROM Interface", "group__eeprom__interface.html", "group__eeprom__interface" ],
    [ "ESPI Driver APIs", "group__espi__interface.html", "group__espi__interface" ],
    [ "Entropy Interface", "group__entropy__interface.html", "group__entropy__interface" ],
    [ "FLASH Interface", "group__flash__interface.html", "group__flash__interface" ],
    [ "FLASH internal Interface", "group__flash__internal__interface.html", "group__flash__internal__interface" ],
    [ "GNA Interface", "group__gna__interface.html", "group__gna__interface" ],
    [ "GPIO Driver APIs", "group__gpio__interface.html", "group__gpio__interface" ],
    [ "Hardware Info Interface", "group__hwinfo__interface.html", "group__hwinfo__interface" ],
    [ "Host Command Peripherals API", "group__ec__host__cmd__periph.html", "group__ec__host__cmd__periph" ],
    [ "I2C EEPROM Slave Driver API", "group__i2c__eeprom__slave__api.html", "group__i2c__eeprom__slave__api" ],
    [ "I2C Interface", "group__i2c__interface.html", "group__i2c__interface" ],
    [ "I2S Interface", "group__i2s__interface.html", "group__i2s__interface" ],
    [ "IPM Interface", "group__ipm__interface.html", "group__ipm__interface" ],
    [ "Keyboard Scan Driver APIs", "group__kscan__interface.html", "group__kscan__interface" ],
    [ "LED Interface", "group__led__interface.html", "group__led__interface" ],
    [ "LED Strip Interface", "group__led__strip__interface.html", "group__led__strip__interface" ],
    [ "MBOX Interface", "group__mbox__interface.html", "group__mbox__interface" ],
    [ "MDIO Interface", "group__mdio__interface.html", "group__mdio__interface" ],
    [ "MODBUS", "group__modbus.html", "group__modbus" ],
    [ "Miscellaneous Drivers APIs", "group__misc__interfaces.html", "group__misc__interfaces" ],
    [ "PCI Express Controller Interface", "group__pcie__controller__interface.html", "group__pcie__controller__interface" ],
    [ "PECI Interface", "group__peci__interface.html", "group__peci__interface" ],
    [ "PS/2 Driver APIs", "group__ps2__interface.html", "group__ps2__interface" ],
    [ "PWM Interface", "group__pwm__interface.html", "group__pwm__interface" ],
    [ "Pin Controller Interface", "group__pinctrl__interface.html", "group__pinctrl__interface" ],
    [ "Pinmux Interface", "group__pinmux__interface.html", "group__pinmux__interface" ],
    [ "Real Time Clock interfaces", "group__rtc__interface.html", "group__rtc__interface" ],
    [ "Regulator Interface", "group__regulator__interface.html", "group__regulator__interface" ],
    [ "SPI Interface", "group__spi__interface.html", "group__spi__interface" ],
    [ "SYSCON Interface", "group__syscon__interface.html", "group__syscon__interface" ],
    [ "Sensor Interface", "group__sensor__interface.html", "group__sensor__interface" ],
    [ "UART Interface", "group__uart__interface.html", "group__uart__interface" ],
    [ "UART Mux Interface", "group__uart__mux__interface.html", "group__uart__mux__interface" ],
    [ "Video Controls", "group__video__controls.html", "group__video__controls" ],
    [ "Video Interface", "group__video__interface.html", "group__video__interface" ],
    [ "Watchdog Interface", "group__watchdog__interface.html", "group__watchdog__interface" ]
];