var group__subsys__tracing__apis =
[
    [ "Conditional Variable Tracing APIs", "group__subsys__tracing__apis__condvar.html", "group__subsys__tracing__apis__condvar" ],
    [ "Event Tracing APIs", "group__subsys__tracing__apis__event.html", "group__subsys__tracing__apis__event" ],
    [ "FIFO Tracing APIs", "group__subsys__tracing__apis__fifo.html", "group__subsys__tracing__apis__fifo" ],
    [ "Heap Tracing APIs", "group__subsys__tracing__apis__heap.html", "group__subsys__tracing__apis__heap" ],
    [ "LIFO Tracing APIs", "group__subsys__tracing__apis__lifo.html", "group__subsys__tracing__apis__lifo" ],
    [ "Mailbox Tracing APIs", "group__subsys__tracing__apis__mbox.html", "group__subsys__tracing__apis__mbox" ],
    [ "Memory Slab Tracing APIs", "group__subsys__tracing__apis__mslab.html", "group__subsys__tracing__apis__mslab" ],
    [ "Message Queue Tracing APIs", "group__subsys__tracing__apis__msgq.html", "group__subsys__tracing__apis__msgq" ],
    [ "Mutex Tracing APIs", "group__subsys__tracing__apis__mutex.html", "group__subsys__tracing__apis__mutex" ],
    [ "PM Device Runtime Tracing APIs", "group__subsys__tracing__apis__pm__device__runtime.html", "group__subsys__tracing__apis__pm__device__runtime" ],
    [ "Pipe Tracing APIs", "group__subsys__tracing__apis__pipe.html", "group__subsys__tracing__apis__pipe" ],
    [ "Poll Tracing APIs", "group__subsys__tracing__apis__poll.html", "group__subsys__tracing__apis__poll" ],
    [ "Queue Tracing APIs", "group__subsys__tracing__apis__queue.html", "group__subsys__tracing__apis__queue" ],
    [ "Semaphore Tracing APIs", "group__subsys__tracing__apis__sem.html", "group__subsys__tracing__apis__sem" ],
    [ "Stack Tracing APIs", "group__subsys__tracing__apis__stack.html", "group__subsys__tracing__apis__stack" ],
    [ "Syscall Tracing APIs", "group__subsys__tracing__apis__syscall.html", "group__subsys__tracing__apis__syscall" ],
    [ "System PM Tracing APIs", "group__subsys__tracing__apis__pm__system.html", "group__subsys__tracing__apis__pm__system" ],
    [ "Thread Tracing APIs", "group__subsys__tracing__apis__thread.html", "group__subsys__tracing__apis__thread" ],
    [ "Timer Tracing APIs", "group__subsys__tracing__apis__timer.html", "group__subsys__tracing__apis__timer" ],
    [ "Work Delayable Tracing APIs", "group__subsys__tracing__apis__work__delayable.html", "group__subsys__tracing__apis__work__delayable" ],
    [ "Work Poll Tracing APIs", "group__subsys__tracing__apis__work__poll.html", "group__subsys__tracing__apis__work__poll" ],
    [ "Work Queue Tracing APIs", "group__subsys__tracing__apis__work__q.html", "group__subsys__tracing__apis__work__q" ],
    [ "Work Tracing APIs", "group__subsys__tracing__apis__work.html", "group__subsys__tracing__apis__work" ],
    [ "sys_trace_idle", "group__subsys__tracing__apis.html#gac9b542f78ed796b4b572de19d295c824", null ],
    [ "sys_trace_isr_enter", "group__subsys__tracing__apis.html#ga37f43a02961a847af3b7de6c474a8da4", null ],
    [ "sys_trace_isr_exit", "group__subsys__tracing__apis.html#ga7113e2760b1a7ffb1bfa108ad9bfb4be", null ],
    [ "sys_trace_isr_exit_to_scheduler", "group__subsys__tracing__apis.html#ga303fe60fd4de8ddcc02c6920656e326d", null ]
];