var group__kernel__apis =
[
    [ "Async polling APIs", "group__poll__apis.html", "group__poll__apis" ],
    [ "Asynchronous Notification APIs", "group__sys__notify__apis.html", "group__sys__notify__apis" ],
    [ "Atomic Services APIs", "group__atomic__apis.html", "group__atomic__apis" ],
    [ "CPU Idling APIs", "group__cpu__idle__apis.html", "group__cpu__idle__apis" ],
    [ "Clock APIs", "group__clock__apis.html", "group__clock__apis" ],
    [ "Condition Variables APIs", "group__condvar__apis.html", "group__condvar__apis" ],
    [ "Event APIs", "group__event__apis.html", "group__event__apis" ],
    [ "FIFO APIs", "group__fifo__apis.html", "group__fifo__apis" ],
    [ "FUTEX APIs", "group__futex__apis.html", "group__futex__apis" ],
    [ "Fatal error APIs", "group__fatal__apis.html", "group__fatal__apis" ],
    [ "Floating Point APIs", "group__float__apis.html", null ],
    [ "Heap APIs", "group__heap__apis.html", "group__heap__apis" ],
    [ "Interrupt Service Routine APIs", "group__isr__apis.html", "group__isr__apis" ],
    [ "LIFO APIs", "group__lifo__apis.html", "group__lifo__apis" ],
    [ "MPSC (Multi producer, single consumer) packet buffer API", "group__mpsc__buf.html", "group__mpsc__buf" ],
    [ "Mailbox APIs", "group__mailbox__apis.html", "group__mailbox__apis" ],
    [ "Memory Slab APIs", "group__mem__slab__apis.html", "group__mem__slab__apis" ],
    [ "Memory domain APIs", "group__mem__domain__apis.html", "group__mem__domain__apis" ],
    [ "Message Queue APIs", "group__msgq__apis.html", "group__msgq__apis" ],
    [ "Mutex APIs", "group__mutex__apis.html", "group__mutex__apis" ],
    [ "On-Off Service APIs", "group__resource__mgmt__onoff__apis.html", "group__resource__mgmt__onoff__apis" ],
    [ "Pipe APIs", "group__pipe__apis.html", "group__pipe__apis" ],
    [ "Queue APIs", "group__queue__apis.html", "group__queue__apis" ],
    [ "Semaphore APIs", "group__semaphore__apis.html", "group__semaphore__apis" ],
    [ "Spinlock APIs", "group__spinlock__apis.html", "group__spinlock__apis" ],
    [ "Stack APIs", "group__stack__apis.html", "group__stack__apis" ],
    [ "Thread APIs", "group__thread__apis.html", "group__thread__apis" ],
    [ "Thread Stack APIs", "group__thread__stack__api.html", "group__thread__stack__api" ],
    [ "Timer APIs", "group__timer__apis.html", "group__timer__apis" ],
    [ "User Mode APIs", "group__usermode__apis.html", "group__usermode__apis" ],
    [ "User mode mutex APIs", "group__user__mutex__apis.html", "group__user__mutex__apis" ],
    [ "User mode semaphore APIs", "group__user__semaphore__apis.html", "group__user__semaphore__apis" ],
    [ "Version APIs", "group__version__apis.html", "group__version__apis" ],
    [ "Work Queue APIs", "group__workqueue__apis.html", "group__workqueue__apis" ]
];