var group__bluetooth =
[
    [ "AUDIO", "group__bt__codec__lc3.html", "group__bt__codec__lc3" ],
    [ "Audio Input Control Service (AICS)", "group__bt__gatt__aics.html", "group__bt__gatt__aics" ],
    [ "Battery Service (BAS)", "group__bt__bas.html", "group__bt__bas" ],
    [ "Bluetooth Audio", "group__bt__audio.html", "group__bt__audio" ],
    [ "Bluetooth Controller", "group__bt__ctrl.html", "group__bt__ctrl" ],
    [ "Bluetooth mesh", "group__bt__mesh.html", "group__bt__mesh" ],
    [ "Bluetooth testing callbacks", "group__bt__test__cb.html", "group__bt__test__cb" ],
    [ "Connection management", "group__bt__conn.html", "group__bt__conn" ],
    [ "Coordinated Set Identification Service  (CSIS)", "group__bt__gatt__csis.html", "group__bt__gatt__csis" ],
    [ "Cryptography", "group__bt__crypto.html", "group__bt__crypto" ],
    [ "Data buffers", "group__bt__buf.html", "group__bt__buf" ],
    [ "Defines and Assigned Numbers", "group__bt__gap__defines.html", "group__bt__gap__defines" ],
    [ "Device Address", "group__bt__addr.html", "group__bt__addr" ],
    [ "Generic Access Profile", "group__bt__gap.html", "group__bt__gap" ],
    [ "Generic Attribute Profile (GATT)", "group__bt__gatt.html", "group__bt__gatt" ],
    [ "HCI RAW channel", "group__hci__raw.html", "group__hci__raw" ],
    [ "HCI drivers", "group__bt__hci__driver.html", "group__bt__hci__driver" ],
    [ "Hands Free Profile (HFP)", "group__bt__hfp.html", "group__bt__hfp" ],
    [ "Heart Rate Service (HRS)", "group__bt__hrs.html", "group__bt__hrs" ],
    [ "ISO", "group__bt__iso.html", "group__bt__iso" ],
    [ "L2CAP", "group__bt__l2cap.html", "group__bt__l2cap" ],
    [ "Media Control Client (MCC)", "group__bt__gatt__mcc.html", "group__bt__gatt__mcc" ],
    [ "Media Control Service (MCS)", "group__bt__mcs.html", "group__bt__mcs" ],
    [ "Microphone Input Control Service (Microphone Input Control Service)", "group__bt__gatt__mics.html", "group__bt__gatt__mics" ],
    [ "Object Transfer Service (OTS)", "group__bt__ots.html", "group__bt__ots" ],
    [ "RFCOMM", "group__bt__rfcomm.html", "group__bt__rfcomm" ],
    [ "Service Discovery Protocol (SDP)", "group__bt__sdp.html", "group__bt__sdp" ],
    [ "UUIDs", "group__bt__uuid.html", "group__bt__uuid" ],
    [ "Volume Control Service (VCS)", "group__bt__gatt__vcs.html", "group__bt__gatt__vcs" ],
    [ "Volume Offset Control Service (VOCS)", "group__bt__gatt__vocs.html", "group__bt__gatt__vocs" ]
];