var group__all__tests =
[
    [ "Common Tests", "group__kernel__common__tests.html", "group__kernel__common__tests" ],
    [ "Device", "group__kernel__device__tests.html", "group__kernel__device__tests" ],
    [ "FIFOs", "group__kernel__fifo__tests.html", "group__kernel__fifo__tests" ],
    [ "Futex", "group__kernel__futex__tests.html", "group__kernel__futex__tests" ],
    [ "Heap Memory Tests", "group__kernel__heap__tests.html", "group__kernel__heap__tests" ],
    [ "Init", "group__kernel__init__tests.html", "group__kernel__init__tests" ],
    [ "LIFOs", "group__kernel__lifo__tests.html", "group__kernel__lifo__tests" ],
    [ "MP Tests", "group__kernel__mp__tests.html", "group__kernel__mp__tests" ],
    [ "Mailbox", "group__kernel__mbox__api.html", "group__kernel__mbox__api" ],
    [ "Memory Slab Tests", "group__kernel__memory__slab__tests.html", "group__kernel__memory__slab__tests" ],
    [ "Message Queue", "group__kernel__message__queue__tests.html", "group__kernel__message__queue__tests" ],
    [ "PIPEs", "group__kernel__pipe__tests.html", "group__kernel__pipe__tests" ],
    [ "Pending tests", "group__kernel__pending__tests.html", "group__kernel__pending__tests" ],
    [ "Poll tests", "group__kernel__poll__tests.html", "group__kernel__poll__tests" ],
    [ "Profiling", "group__kernel__profiling__tests.html", "group__kernel__profiling__tests" ],
    [ "Queues", "group__kernel__queue__tests.html", "group__kernel__queue__tests" ],
    [ "SMP Tests", "group__kernel__smp__module__tests.html", "group__kernel__smp__module__tests" ],
    [ "SMP Tests", "group__kernel__smp__integration__tests.html", "group__kernel__smp__integration__tests" ],
    [ "SMP Tests", "group__kernel__smp__tests.html", "group__kernel__smp__tests" ],
    [ "Scheduling Tests", "group__kernel__sched__tests.html", "group__kernel__sched__tests" ],
    [ "Semaphore", "group__kernel__sys__sem__tests.html", "group__kernel__sys__sem__tests" ],
    [ "Semaphore", "group__kernel__sys__events__tests.html", null ],
    [ "Sleep Tests", "group__kernel__sleep__tests.html", "group__kernel__sleep__tests" ],
    [ "Spinlock Tests", "group__kernel__spinlock__tests.html", "group__kernel__spinlock__tests" ],
    [ "Stacks", "group__kernel__stack__tests.html", "group__kernel__stack__tests" ],
    [ "Thread Context Tests", "group__kernel__threadcontext__tests.html", "group__kernel__threadcontext__tests" ],
    [ "Threads", "group__kernel__thread__tests.html", "group__kernel__thread__tests" ],
    [ "Tickless", "group__kernel__tickless__tests.html", "group__kernel__tickless__tests" ],
    [ "Timer", "group__kernel__timer__tests.html", "group__kernel__timer__tests" ],
    [ "Workqueue", "group__kernel__workqueue__tests.html", "group__kernel__workqueue__tests" ],
    [ "XIP Tests", "group__kernel__xip__tests.html", "group__kernel__xip__tests" ],
    [ "api Tests", "group__k__heap.html", null ],
    [ "events", "group__kernel__event__tests.html", null ]
];