var modules =
[
    [ "Architecture Interface", "group__arch-interface.html", "group__arch-interface" ],
    [ "Audio", "group__audio__interface.html", "group__audio__interface" ],
    [ "Backing Store APIs", "group__mem-demand-paging-backing-store.html", "group__mem-demand-paging-backing-store" ],
    [ "Balanced Red/Black Tree", "group__rbtree__apis.html", "group__rbtree__apis" ],
    [ "Bluetooth APIs", "group__bluetooth.html", "group__bluetooth" ],
    [ "CAN ISO-TP Interface", "group__can__isotp.html", "group__can__isotp" ],
    [ "CPU Power Management", "group__power__management__cpu__api.html", "group__power__management__cpu__api" ],
    [ "Checksum", "group__checksum.html", "group__checksum" ],
    [ "Coredump APIs", "group__coredump__apis.html", "group__coredump__apis" ],
    [ "Crypto", "group__crypto.html", "group__crypto" ],
    [ "Demand Paging APIs", "group__mem-demand-paging.html", "group__mem-demand-paging" ],
    [ "Device Driver APIs", "group__io__interfaces.html", "group__io__interfaces" ],
    [ "Device Model APIs", "group__device__model.html", "group__device__model" ],
    [ "Device memory-mapped IO management", "group__device-mmio.html", "group__device-mmio" ],
    [ "Devicetree", "group__devicetree.html", "group__devicetree" ],
    [ "Disk Access Interface", "group__disk__access__interface.html", "group__disk__access__interface" ],
    [ "Disk Driver Interface", "group__disk__driver__interface.html", "group__disk__driver__interface" ],
    [ "Display Drivers", "group__display__interfaces.html", "group__display__interfaces" ],
    [ "Doubly-linked list", "group__doubly-linked-list__apis.html", "group__doubly-linked-list__apis" ],
    [ "Emulator interface", "group__io__emulators.html", "group__io__emulators" ],
    [ "Error numbers", "group__system__errno.html", "group__system__errno" ],
    [ "Eviction Algorithm APIs", "group__mem-demand-paging-eviction.html", "group__mem-demand-paging-eviction" ],
    [ "File System APIs", "group__file__system__api.html", "group__file__system__api" ],
    [ "File System Storage", "group__file__system__storage.html", "group__file__system__storage" ],
    [ "Flagged Single-linked list", "group__flagged-single-linked-list__apis.html", "group__flagged-single-linked-list__apis" ],
    [ "Formatted Output APIs", "group__cbprintf__apis.html", "group__cbprintf__apis" ],
    [ "Hawkbit Firmware Over-the-Air", "group__hawkbit.html", "group__hawkbit" ],
    [ "Heap Listener APIs", "group__heap__listener__apis.html", "group__heap__listener__apis" ],
    [ "IPC service APIs", "group__ipc__service__api.html", "group__ipc__service__api" ],
    [ "IPC service RPMsg API", "group__ipc__service__rpmsg__api.html", "group__ipc__service__rpmsg__api" ],
    [ "IPC service static VRINGs API", "group__ipc__service__static__vrings__api.html", "group__ipc__service__static__vrings__api" ],
    [ "Iterable Sections APIs", "group__iterable__section__apis.html", "group__iterable__section__apis" ],
    [ "Kernel APIs", "group__kernel__apis.html", "group__kernel__apis" ],
    [ "Logging", "group__logging.html", "group__logging" ],
    [ "Memory Blocks APIs", "group__mem__blocks__apis.html", "group__mem__blocks__apis" ],
    [ "Memory Management Driver APIs", "group__mm__drv__apis.html", "group__mm__drv__apis" ],
    [ "Networking", "group__networking.html", "group__networking" ],
    [ "RPMsg service APIs", "group__rpmsg__service__api.html", "group__rpmsg__service__api" ],
    [ "Ring Buffer APIs", "group__ring__buffer__apis.html", "group__ring__buffer__apis" ],
    [ "Shared multi-heap interface", "group__shared__multi__heap.html", "group__shared__multi__heap" ],
    [ "Shell API", "group__shell__api.html", "group__shell__api" ],
    [ "Single-linked list", "group__single-linked-list__apis.html", "group__single-linked-list__apis" ],
    [ "Stream to flash interface", "group__stream__flash.html", "group__stream__flash" ],
    [ "Structured Data", "group__structured__data.html", "group__structured__data" ],
    [ "Subsystems", "group__subsys.html", "group__subsys" ],
    [ "Task Watchdog APIs", "group__task__wdt__api.html", "group__task__wdt__api" ],
    [ "Thread analyzer", "group__thread__analyzer.html", "group__thread__analyzer" ],
    [ "Time Utility APIs", "group__timeutil__apis.html", "group__timeutil__apis" ],
    [ "Timing APIs", "group__timing__api.html", "group__timing__api" ],
    [ "USB HID class API", "group__usb__hid__class.html", "group__usb__hid__class" ],
    [ "USB HID common definitions", "group__usb__hid__definitions.html", "group__usb__hid__definitions" ],
    [ "Utility Functions", "group__sys-util.html", "group__sys-util" ],
    [ "Zephyr Tests", "group__all__tests.html", "group__all__tests" ],
    [ "Zephyr testing suite", "group__ztest.html", "group__ztest" ],
    [ "flash area Interface", "group__flash__area__api.html", "group__flash__area__api" ],
    [ "ivshmem reference API", "group__ivshmem.html", "group__ivshmem" ]
];