var searchData=
[
  ['dac_5fchannel_5fcfg_0',['dac_channel_cfg',['../structdac__channel__cfg.html',1,'']]],
  ['delayed_5ftest_5fitem_1',['delayed_test_item',['../structdelayed__test__item.html',1,'']]],
  ['device_2',['device',['../structdevice.html',1,'']]],
  ['device_5fstate_3',['device_state',['../structdevice__state.html',1,'']]],
  ['dfu_5fruntime_5fdescriptor_4',['dfu_runtime_descriptor',['../structdfu__runtime__descriptor.html',1,'']]],
  ['disk_5finfo_5',['disk_info',['../structdisk__info.html',1,'']]],
  ['disk_5foperations_6',['disk_operations',['../structdisk__operations.html',1,'']]],
  ['display_5fbuffer_5fdescriptor_7',['display_buffer_descriptor',['../structdisplay__buffer__descriptor.html',1,'']]],
  ['display_5fcapabilities_8',['display_capabilities',['../structdisplay__capabilities.html',1,'']]],
  ['display_5fdriver_5fapi_9',['display_driver_api',['../structdisplay__driver__api.html',1,'']]],
  ['dma_5fblock_5fconfig_10',['dma_block_config',['../structdma__block__config.html',1,'']]],
  ['dma_5fconfig_11',['dma_config',['../structdma__config.html',1,'']]],
  ['dma_5fcontext_12',['dma_context',['../structdma__context.html',1,'']]],
  ['dma_5fstatus_13',['dma_status',['../structdma__status.html',1,'']]],
  ['dmic_5fcfg_14',['dmic_cfg',['../structdmic__cfg.html',1,'']]],
  ['dns_5faddrinfo_15',['dns_addrinfo',['../structdns__addrinfo.html',1,'']]],
  ['dns_5fpending_5fquery_16',['dns_pending_query',['../structdns__resolve__context_1_1dns__pending__query.html',1,'dns_resolve_context']]],
  ['dns_5fresolve_5fcontext_17',['dns_resolve_context',['../structdns__resolve__context.html',1,'']]],
  ['dsa_5fslave_5fconfig_18',['dsa_slave_config',['../structdsa__slave__config.html',1,'']]],
  ['dummy_5fapi_19',['dummy_api',['../structdummy__api.html',1,'']]],
  ['dummy_5fdriver_5fapi_20',['dummy_driver_api',['../structdummy__driver__api.html',1,'']]]
];
