var searchData=
[
  ['dac_20driver_20apis_0',['DAC driver APIs',['../group__dac__interface.html',1,'']]],
  ['data_20buffers_1',['Data buffers',['../group__bt__buf.html',1,'']]],
  ['defines_20and_20assigned_20numbers_2',['Defines and Assigned Numbers',['../group__bt__gap__defines.html',1,'']]],
  ['demand_20paging_20apis_3',['Demand Paging APIs',['../group__mem-demand-paging.html',1,'']]],
  ['dependency_20tracking_4',['Dependency tracking',['../group__devicetree-dep-ord.html',1,'']]],
  ['device_5',['Device',['../group__kernel__device__tests.html',1,'(Global Namespace)'],['../group__subsys__pm__device.html',1,'(Global Namespace)']]],
  ['device_20address_6',['Device Address',['../group__bt__addr.html',1,'']]],
  ['device_20driver_20apis_7',['Device Driver APIs',['../group__io__interfaces.html',1,'']]],
  ['device_20memory_2dmapped_20io_20management_8',['Device memory-mapped IO management',['../group__device-mmio.html',1,'']]],
  ['device_20model_20apis_9',['Device Model APIs',['../group__device__model.html',1,'']]],
  ['device_20runtime_10',['Device Runtime',['../group__subsys__pm__device__runtime.html',1,'']]],
  ['devicetree_11',['Devicetree',['../group__devicetree.html',1,'']]],
  ['devicetree_20clocks_20api_12',['Devicetree Clocks API',['../group__devicetree-clocks.html',1,'']]],
  ['devicetree_20dma_20api_13',['Devicetree DMA API',['../group__devicetree-dmas.html',1,'']]],
  ['devicetree_20fixed_20partition_20api_14',['Devicetree Fixed Partition API',['../group__devicetree-fixed-partition.html',1,'']]],
  ['devicetree_20gpio_20api_15',['Devicetree GPIO API',['../group__devicetree-gpio.html',1,'']]],
  ['devicetree_20io_20channels_20api_16',['Devicetree IO Channels API',['../group__devicetree-io-channels.html',1,'']]],
  ['devicetree_20pwms_20api_17',['Devicetree PWMs API',['../group__devicetree-pwms.html',1,'']]],
  ['devicetree_20spi_20api_18',['Devicetree SPI API',['../group__devicetree-spi.html',1,'']]],
  ['dhcpv4_19',['DHCPv4',['../group__dhcpv4.html',1,'']]],
  ['digital_20microphone_20interface_20',['Digital Microphone Interface',['../group__audio__dmic__interface.html',1,'']]],
  ['disk_20access_20interface_21',['Disk Access Interface',['../group__disk__access__interface.html',1,'']]],
  ['disk_20driver_20interface_22',['Disk Driver Interface',['../group__disk__driver__interface.html',1,'']]],
  ['display_20drivers_23',['Display Drivers',['../group__display__interfaces.html',1,'']]],
  ['display_20interface_24',['Display Interface',['../group__display__interface.html',1,'']]],
  ['dma_20interface_25',['DMA Interface',['../group__dma__interface.html',1,'']]],
  ['dns_20resolve_20library_26',['DNS Resolve Library',['../group__dns__resolve.html',1,'']]],
  ['dns_20service_20discovery_27',['DNS Service Discovery',['../group__dns__sd.html',1,'']]],
  ['doubly_2dlinked_20list_28',['Doubly-linked list',['../group__doubly-linked-list__apis.html',1,'']]],
  ['dummy_20l2_2fdriver_20support_20functions_29',['Dummy L2/driver Support Functions',['../group__dummy.html',1,'']]],
  ['dynamic_20pin_20control_30',['Dynamic Pin Control',['../group__pinctrl__interface__dynamic.html',1,'']]]
];
