var searchData=
[
  ['package_20flags_2e_0',['Package flags.',['../group__CBPRINTF__MUST__RUNTIME__PACKAGE__FLAGS.html',1,'(Global Namespace)'],['../group__CBPRINTF__PACKAGE__FLAGS.html',1,'(Global Namespace)']]],
  ['pci_20express_20controller_20interface_1',['PCI Express Controller Interface',['../group__pcie__controller__interface.html',1,'']]],
  ['peci_20interface_2',['PECI Interface',['../group__peci__interface.html',1,'']]],
  ['pending_20tests_3',['Pending tests',['../group__kernel__pending__tests.html',1,'']]],
  ['pin_20control_4',['Pin control',['../group__devicetree-pinctrl.html',1,'']]],
  ['pin_20controller_20interface_5',['Pin Controller Interface',['../group__pinctrl__interface.html',1,'']]],
  ['pinmux_20interface_6',['Pinmux Interface',['../group__pinmux__interface.html',1,'']]],
  ['pipe_20apis_7',['Pipe APIs',['../group__pipe__apis.html',1,'']]],
  ['pipe_20tracing_20apis_8',['Pipe Tracing APIs',['../group__subsys__tracing__apis__pipe.html',1,'']]],
  ['pipes_9',['PIPEs',['../group__kernel__pipe__tests.html',1,'']]],
  ['pm_20device_20runtime_20tracing_20apis_10',['PM Device Runtime Tracing APIs',['../group__subsys__tracing__apis__pm__device__runtime.html',1,'']]],
  ['poll_20tests_11',['Poll tests',['../group__kernel__poll__tests.html',1,'']]],
  ['poll_20tracing_20apis_12',['Poll Tracing APIs',['../group__subsys__tracing__apis__poll.html',1,'']]],
  ['polling_20uart_20api_13',['Polling UART API',['../group__uart__polling.html',1,'']]],
  ['power_20management_20_28pm_29_14',['Power Management (PM)',['../group__subsys__pm.html',1,'']]],
  ['ppp_20l2_2fdriver_20support_20functions_15',['PPP L2/driver Support Functions',['../group__ppp.html',1,'']]],
  ['profiling_16',['Profiling',['../group__kernel__profiling__tests.html',1,'']]],
  ['promiscuous_20mode_17',['Promiscuous mode',['../group__promiscuous.html',1,'']]],
  ['property_20accessors_18',['Property accessors',['../group__devicetree-generic-prop.html',1,'']]],
  ['provisioning_19',['Provisioning',['../group__bt__mesh__prov.html',1,'']]],
  ['proxy_20',['Proxy',['../group__bt__mesh__proxy.html',1,'']]],
  ['ps_2f2_20driver_20apis_21',['PS/2 Driver APIs',['../group__ps2__interface.html',1,'']]],
  ['ptp_20time_22',['PTP time',['../group__ptp__time.html',1,'']]],
  ['pwm_20interface_23',['PWM Interface',['../group__pwm__interface.html',1,'']]]
];
